export { default as About } from "./About"
export { default as Contact } from "./Contact"
export { default as Header } from "./Header"
export { default as Hero } from "./Hero"
export { default as Particles } from "./Particles"
export { default as Projects } from "./Projects"
export { default as WrapperGSAP } from "./WrapperGSAP"